updated German translation
njthomson/SrvSurvey pull request #157
Opened 2024-12-24 18:35 UTC by InvestigateXM

updated German translations to use official terms used in Elite in German as well as fixing some translation errors due to missing context

only translated the strings that are present in the dedicated file for them (/Properties), as I don't wanna break the rest of the program if I start digging around for the other strings

2025-01-02 08:09 UTC, njthomson commented on SrvSurvey/Properties/Misc.de.resx
> +Möchtest du ihn erstellen?</comment>
The comment needs to be the original English phrase - this is how I tell when new translations are required.

2025-01-02 08:11 UTC, njthomson commented on SrvSurvey/Properties/Misc.de.resx
> +    <comment>Ziel:</comment>
The `comment` line should remain in English, but should the `value` line above change?

2025-01-02 08:15 UTC, njthomson requested changes
Danke @InvestigateXM for these updates! There are 2 places I noticed where you translated the comment rather than the original phrase. These need to remain as the original English phrase - this is how I tell when new translations are required.

2025-01-03 00:00 UTC, InvestigateXM commented
My mistake @njthomson, thats what I get for doing stuff during the night. Newest commit should have fixed these issues :)

2025-01-04 03:42 UTC, njthomson approved these changes

2025-01-04 06:03 UTC, merged